/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as MaisonRouteImport } from './routes/maison'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HommeRouteImport } from './routes/homme'
import { Route as FemmeRouteImport } from './routes/femme'
import { Route as EnfantRouteImport } from './routes/enfant'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BienEtreRouteImport } from './routes/bien-etre'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BrandSlugRouteImport } from './routes/brand.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMarqueeRouteImport } from './routes/admin.marquee'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisonRoute = MaisonRouteImport.update({
  id: '/maison',
  path: '/maison',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HommeRoute = HommeRouteImport.update({
  id: '/homme',
  path: '/homme',
  getParentRoute: () => rootRouteImport,
} as any)
const FemmeRoute = FemmeRouteImport.update({
  id: '/femme',
  path: '/femme',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfantRoute = EnfantRouteImport.update({
  id: '/enfant',
  path: '/enfant',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BienEtreRoute = BienEtreRouteImport.update({
  id: '/bien-etre',
  path: '/bien-etre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarqueeRoute = AdminMarqueeRouteImport.update({
  id: '/marquee',
  path: '/marquee',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bien-etre': typeof BienEtreRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/enfant': typeof EnfantRoute
  '/femme': typeof FemmeRoute
  '/homme': typeof HommeRoute
  '/login': typeof LoginRoute
  '/maison': typeof MaisonRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/marquee': typeof AdminMarqueeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bien-etre': typeof BienEtreRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/enfant': typeof EnfantRoute
  '/femme': typeof FemmeRoute
  '/homme': typeof HommeRoute
  '/login': typeof LoginRoute
  '/maison': typeof MaisonRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/marquee': typeof AdminMarqueeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/bien-etre': typeof BienEtreRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/enfant': typeof EnfantRoute
  '/femme': typeof FemmeRoute
  '/homme': typeof HommeRoute
  '/login': typeof LoginRoute
  '/maison': typeof MaisonRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/register': typeof RegisterRoute
  '/wishlist': typeof WishlistRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/marquee': typeof AdminMarqueeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/new': typeof AdminProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bien-etre'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/enfant'
    | '/femme'
    | '/homme'
    | '/login'
    | '/maison'
    | '/order-confirmation'
    | '/profile'
    | '/promotions'
    | '/register'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/hero'
    | '/admin/marquee'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/brand/$slug'
    | '/category/$slug'
    | '/legal/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/admin/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bien-etre'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/enfant'
    | '/femme'
    | '/homme'
    | '/login'
    | '/maison'
    | '/order-confirmation'
    | '/profile'
    | '/promotions'
    | '/register'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/hero'
    | '/admin/marquee'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/brand/$slug'
    | '/category/$slug'
    | '/legal/$slug'
    | '/product/$slug'
    | '/admin'
    | '/admin/products/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bien-etre'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/enfant'
    | '/femme'
    | '/homme'
    | '/login'
    | '/maison'
    | '/order-confirmation'
    | '/profile'
    | '/promotions'
    | '/register'
    | '/wishlist'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/hero'
    | '/admin/marquee'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/brand/$slug'
    | '/category/$slug'
    | '/legal/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/admin/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BienEtreRoute: typeof BienEtreRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  EnfantRoute: typeof EnfantRoute
  FemmeRoute: typeof FemmeRoute
  HommeRoute: typeof HommeRoute
  LoginRoute: typeof LoginRoute
  MaisonRoute: typeof MaisonRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  RegisterRoute: typeof RegisterRoute
  WishlistRoute: typeof WishlistRoute
  BrandSlugRoute: typeof BrandSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maison': {
      id: '/maison'
      path: '/maison'
      fullPath: '/maison'
      preLoaderRoute: typeof MaisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homme': {
      id: '/homme'
      path: '/homme'
      fullPath: '/homme'
      preLoaderRoute: typeof HommeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/femme': {
      id: '/femme'
      path: '/femme'
      fullPath: '/femme'
      preLoaderRoute: typeof FemmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfant': {
      id: '/enfant'
      path: '/enfant'
      fullPath: '/enfant'
      preLoaderRoute: typeof EnfantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bien-etre': {
      id: '/bien-etre'
      path: '/bien-etre'
      fullPath: '/bien-etre'
      preLoaderRoute: typeof BienEtreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marquee': {
      id: '/admin/marquee'
      path: '/marquee'
      fullPath: '/admin/marquee'
      preLoaderRoute: typeof AdminMarqueeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface AdminProductsRouteChildren {
  AdminProductsNewRoute: typeof AdminProductsNewRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsNewRoute: AdminProductsNewRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminMarqueeRoute: typeof AdminMarqueeRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminMarqueeRoute: AdminMarqueeRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BienEtreRoute: BienEtreRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  EnfantRoute: EnfantRoute,
  FemmeRoute: FemmeRoute,
  HommeRoute: HommeRoute,
  LoginRoute: LoginRoute,
  MaisonRoute: MaisonRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  RegisterRoute: RegisterRoute,
  WishlistRoute: WishlistRoute,
  BrandSlugRoute: BrandSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
